"""create tables for menus db

Revision ID: a3284ffd9683
Revises: 
Create Date: 2023-01-20 21:05:20.937211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3284ffd9683'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menus_item', sa.String(length=64), nullable=False),
    sa.Column('menus_description', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menus_item', name='_menus_item_uc')
    )
    op.create_table('submenus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('menus_id', sa.Integer(), nullable=False),
    sa.Column('submenus_item', sa.String(length=64), nullable=False),
    sa.Column('submenus_description', sa.String(length=256), nullable=True),
    sa.ForeignKeyConstraint(['menus_id'], ['menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dishes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submenus_id', sa.Integer(), nullable=False),
    sa.Column('dish_name', sa.String(length=64), nullable=False),
    sa.Column('dish_description', sa.String(length=256), nullable=True),
    sa.Column('dish_price', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['submenus_id'], ['submenus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dish_name', name='_dish_name_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dishes')
    op.drop_table('submenus')
    op.drop_table('menus')
    # ### end Alembic commands ###
